import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles({
  navbar: {
    position: "fixed",
    zIndex: 1,
    top: 0,
    left: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: 64,
    background: "#19191c",
    color: "#f9f9f9",
    fontFamily: "Poppins",
  },
  overlay: {
    position: "fixed",
    zIndex: 2,
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: "rgba(0, 0, 0, 0.5)",
    visibility: "hidden",
    opacity: 0,
    transition: "0.5s",
  },
  openOverlay: {
    visibility: "visible",
    opacity: 1,
  },
  burger: {
    border: "none",
    position: "absolute",
    top: 0,
    left: 0,
    display: "grid",
    placeItems: "center",
    width: 64,
    height: 64,
    padding: 0,
    background: "transparent",
    color: "inherit",
    cursor: "pointer",
  },
  title: {
    margin: 0,
    fontSize: 16,
  },
  menu: {
    position: "fixed",
    zIndex: 3,
    top: 0,
    left: 0,
    transform: "translate(-100%, 0)",
    width: 270,
    height: "100%",
    padding: 20,
    display: "flex",
    gap: 8,
    flexDirection: "column",
    alignItems: "flex-start",
    background: "#000",
    visibility: "hidden",
    transition: "all 0.3s",
  },
  openMenu: {
    transform: "translate(0, 0)",
    visibility: "visible",
  },
  button: {
    color: "rgba(255, 255, 255, 0.5)",
    padding: "0 8px",
    transition: "all 0.3s",
    fontFamily: "inherit",
    background: "transparent",
    cursor: "pointer",
    border: 0,
  },
  active: {
    color: "inherit",
    "&:hover": {
      color: "rgba(255, 255, 255, 0.75)",
    },
  },
  "@media (min-width:600px)": {
    navbar: {
      justifyContent: "space-between",
      padding: "0 0 0 16px",
    },
    overlay: {
      display: "none",
    },
    burger: {
      display: "none",
    },
    menu: {
      position: "static",
      transform: "translate(0, 0)",
      width: "auto",
      background: "transparent",
      flexDirection: "row",
      visibility: "visible",
    },
  },
});